workflows:
  flutter-shorebird-deploy:
    name: Flutter Shorebird Deploy
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - shorebird_credentials # Grupo contendo a variável SHOREBIRD_TOKEN
    working_directory: shorebird_example_flutter
    scripts:
      - name: Install dependencies
        script: |
          flutter --version
          flutter pub get
      - name: Install Shorebird CLI
        script: |
          curl -sSf https://install.shorebird.dev | bash
          export PATH="$HOME/.shorebird/bin:$PATH"
          shorebird --version
      - name: Authenticate Shorebird
        script: |
          shorebird login --access-token "$SHOREBIRD_TOKEN"
      - name: Shorebird release for Android
        script: |
          shorebird release android
      - name: Shorebird release for iOS
        script: |
          shorebird release ios
    publishing:
      email:
        recipients:
          - "luisgustavodevbr@gmail.com"
